services:
    _defaults:
        autowire: true
        autoconfigure: true

    DirkKlemmt\ContaoMmenuBundle\EventListener\:
        resource: '../../EventListener/*'

    DirkKlemmt\ContaoMmenuBundle\Migration\:
        resource: '../../Migration/*'

    DirkKlemmt\ContaoMmenuBundle\DataContainer\ModuleCallbacks:
        public: true
