services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [ 'setFramework', [ '@contao.framework' ] ]

    DirkKlemmt\ContaoMmenuBundle\EventListener\:
        resource: '../../EventListener/*'

    DirkKlemmt\ContaoMmenuBundle\Migration\:
        resource: '../../Migration/*'
